version: '3.7'
services:
    survey_mongodb:
        image: mongo:latest
        env_file:
            - mongo.env
        ports:
            - 27017:27017
        volumes:
            - ./db:/data/db